website/music/urls.py
from django.conf.urls import url
from . import views


app_name = 'music'

urlpatterns = [
    # main page 
    url(r'^$', views.index, name='index'),

    # /music/someID
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),

     # favoriting a song
    url(r'^(?P<album_id>[0-9]+)/favorite/$', views.detail, name='favorite')
]

website/website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),

]

website/music/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1500)

    def __str__(self):
        return self.album_title + " - " + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=30)
    song_title = models.CharField(max_length=500)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

website/music/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
#raising a 404 Error
from django.shortcuts import render, get_object_or_404
from .models import Album, Song

def index(request):
    # connection to the database
    all_albums = Album.objects.all()

    #dictionary
    context = {'all_albums': all_albums}

    #rendering html page
    return render(request, 'music/index.html', context)

def detail(request, album_id):
    #shortcut of try and except 
    album = get_object_or_404(Album, pk=album_id)
    return render(request, 'music/detail.html', {'album': album})

def favorite(request, song_id):
    song = get_object_or_404(Song, pk=song_id)
    try:
        if song.is_favorite:
            song.is_favorite = False
        else:
            song.is_favorite = True
        song.save()
    except (KeyError, Song.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})

website/music/templates/music/detail.html
<img src="{{ album.album_logo }}">

<h1>{{ album.album_title }}</h1>

<h3>Artist: {{ album.artist}}</h3>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'music:favorite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}" />
        <label for="song{{ forloop.counter }}">
            {{ song.song_title }}
            {% if song.is_favorite %}
                <img src="http://i.imgur.com/b9b13Rd.png" />
            {% endif %}
        </label><br>
    {% endfor %}
    <input type="submit" value="Favorite">
</form>

website/music/templates/music/index.html
{% if all_albums %}
    <h3>Here Are All My Albums</h3>
    <ul>
        <!-- Django for loop -->
        {% for album in all_albums %}
            <li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p> You dont't have any albums </p>
{% endif %}
    